// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using amazonppcapi.Models;

#nullable disable

namespace amazonppcapi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230730172212_InitialCreate5")]
    partial class InitialCreate5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("amazonppcapi.Models.Entities.AdvertisedProductReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Apr7DayAdvertisedSkuSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Apr7DayAdvertisedSkuUnits")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Apr7DayConversionRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Apr7DayOtherSkuSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Apr7DayOtherSkuUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("Apr7DayTotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Apr7DayTotalSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Apr7DayTotalUnits")
                        .HasColumnType("integer");

                    b.Property<string>("AprAdGroupName")
                        .HasColumnType("text");

                    b.Property<string>("AprAdvertisedAsin")
                        .HasColumnType("text");

                    b.Property<string>("AprAdvertisedSku")
                        .HasColumnType("text");

                    b.Property<string>("AprCampaignName")
                        .HasColumnType("text");

                    b.Property<int?>("AprClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AprCpc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AprCtr")
                        .HasColumnType("numeric");

                    b.Property<string>("AprCurrency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AprDate")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("AprImpressions")
                        .HasColumnType("integer");

                    b.Property<string>("AprPortfolioName")
                        .HasColumnType("text");

                    b.Property<decimal?>("AprSpend")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AprTotalAdvertisingCostOfSalesAcos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AprTotalReturnOnAdvertisingSpendRoas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("AdvertisedProductsReports");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.BudgetReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Br7DayTotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Br7DayTotalSales")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BrAverageTimeInBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("BrBiddingStrategy")
                        .HasColumnType("text");

                    b.Property<decimal?>("BrBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("BrCampaignName")
                        .HasColumnType("text");

                    b.Property<string>("BrCampaignType")
                        .HasColumnType("text");

                    b.Property<int?>("BrClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BrCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BrCtr")
                        .HasColumnType("numeric");

                    b.Property<string>("BrCurrency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("BrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BrEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BrEstimatedMissedClicksRangeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("BrEstimatedMissedClicksRangeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("BrEstimatedMissedImpressionsRangeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("BrEstimatedMissedImpressionsRangeMin")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BrEstimatedMissedSalesRangeMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BrEstimatedMissedSalesRangeMin")
                        .HasColumnType("numeric");

                    b.Property<int?>("BrImpressions")
                        .HasColumnType("integer");

                    b.Property<int?>("BrLastYearClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BrLastYearCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<int?>("BrLastYearImpressions")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BrLastYearSpend")
                        .HasColumnType("numeric");

                    b.Property<string>("BrPortfolioName")
                        .HasColumnType("text");

                    b.Property<decimal?>("BrRecommendedBudget")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BrSpend")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("BrStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BrStatus")
                        .HasColumnType("text");

                    b.Property<string>("BrTargetingType")
                        .HasColumnType("text");

                    b.Property<decimal?>("BrTotalAdvertisingCostOfSalesAcos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BrTotalReturnOnAdvertisingSpendRoas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("BudgetReport");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.CampaignReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("Cr7DayTotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Cr7DayTotalSales")
                        .HasColumnType("numeric");

                    b.Property<string>("CrBiddingStrategy")
                        .HasColumnType("text");

                    b.Property<decimal?>("CrBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("CrCampaignName")
                        .HasColumnType("text");

                    b.Property<string>("CrCampaignType")
                        .HasColumnType("text");

                    b.Property<int?>("CrClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CrCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CrCtr")
                        .HasColumnType("numeric");

                    b.Property<string>("CrCurrency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CrEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CrImpressions")
                        .HasColumnType("integer");

                    b.Property<int?>("CrLastYearClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CrLastYearCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<int?>("CrLastYearImpressions")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CrLastYearSpend")
                        .HasColumnType("numeric");

                    b.Property<string>("CrPortfolioName")
                        .HasColumnType("text");

                    b.Property<decimal?>("CrSpend")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("CrStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrStatus")
                        .HasColumnType("text");

                    b.Property<string>("CrTargetingType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CrTotalAdvertisingCostOfSalesAcos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CrTotalReturnOnAdvertisingSpendRoas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("CampaignReport");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.GrossInvalidTrafficReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("GitrCampaignName")
                        .HasColumnType("text");

                    b.Property<int?>("GitrClicks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("GitrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GitrGrossClicks")
                        .HasColumnType("integer");

                    b.Property<int?>("GitrGrossImpressions")
                        .HasColumnType("integer");

                    b.Property<int?>("GitrImpressions")
                        .HasColumnType("integer");

                    b.Property<decimal?>("GitrInvalidClickRate")
                        .HasColumnType("numeric");

                    b.Property<int?>("GitrInvalidClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("GitrInvalidImpressionRate")
                        .HasColumnType("numeric");

                    b.Property<int?>("GitrInvalidImpressions")
                        .HasColumnType("integer");

                    b.Property<string>("GitrStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GrossInvalidTrafficReport");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.PerformanceOverTimeReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("PotrClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PotrCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("PotrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PotrSpend")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PerformanceOverTimeReport");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.PlacementReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("Pr7DayTotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pr7DayTotalSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Pr7DayTotalUnits")
                        .HasColumnType("integer");

                    b.Property<string>("PrBiddingStrategy")
                        .HasColumnType("text");

                    b.Property<string>("PrCampaignName")
                        .HasColumnType("text");

                    b.Property<int?>("PrClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<string>("PrCurrency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PrImpressions")
                        .HasColumnType("integer");

                    b.Property<string>("PrPlacements")
                        .HasColumnType("text");

                    b.Property<string>("PrPortfolioName")
                        .HasColumnType("text");

                    b.Property<decimal?>("PrSpend")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrTotalAdvertisingCostOfSalesAcos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrTotalReturnOnAdvertisingSpendRoas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PlacementReport");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.PurchasedProductReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("Ppr7DayOtherSkuOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Ppr7DayOtherSkuSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Ppr7DayOtherSkuUnits")
                        .HasColumnType("integer");

                    b.Property<string>("PprAdGroupName")
                        .HasColumnType("text");

                    b.Property<string>("PprAdvertisedAsin")
                        .HasColumnType("text");

                    b.Property<string>("PprAdvertisedSku")
                        .HasColumnType("text");

                    b.Property<string>("PprCampaignName")
                        .HasColumnType("text");

                    b.Property<string>("PprCurrency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PprDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PprMatchType")
                        .HasColumnType("text");

                    b.Property<string>("PprPortfolioName")
                        .HasColumnType("text");

                    b.Property<string>("PprPurchasedAsin")
                        .HasColumnType("text");

                    b.Property<string>("PprTargeting")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PurchasedProductReport");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.SearchTermImpressionShareReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Isr7DayConversionRate")
                        .HasColumnType("numeric");

                    b.Property<int?>("Isr7DayTotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Isr7DayTotalSales")
                        .HasColumnType("numeric");

                    b.Property<string>("IsrAdGroupName")
                        .HasColumnType("text");

                    b.Property<string>("IsrCampaignName")
                        .HasColumnType("text");

                    b.Property<decimal?>("IsrClickThruRateCtr")
                        .HasColumnType("numeric");

                    b.Property<int?>("IsrClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("IsrCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<string>("IsrCurrency")
                        .HasColumnType("text");

                    b.Property<string>("IsrCustomerSearchTerm")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("IsrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IsrImpressions")
                        .HasColumnType("integer");

                    b.Property<string>("IsrMatchType")
                        .HasColumnType("text");

                    b.Property<string>("IsrPortfolioName")
                        .HasColumnType("text");

                    b.Property<int?>("IsrSearchTermImpressionRank")
                        .HasColumnType("integer");

                    b.Property<decimal?>("IsrSearchTermImpressionShare")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IsrSpend")
                        .HasColumnType("numeric");

                    b.Property<string>("IsrTargeting")
                        .HasColumnType("text");

                    b.Property<decimal?>("IsrTotalAdvertisingCostOfSalesAcos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IsrTotalReturnOnAdvertisingSpendRoas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SearchTermImpressionShareReport");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.SearchTermReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Str7DayAdvertisedSkuSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Str7DayAdvertisedSkuUnits")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Str7DayConversionRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Str7DayOtherSkuSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Str7DayOtherSkuUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("Str7DayTotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Str7DayTotalSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Str7DayTotalUnits")
                        .HasColumnType("integer");

                    b.Property<string>("StrAdGroupName")
                        .HasColumnType("text");

                    b.Property<string>("StrCampaignName")
                        .HasColumnType("text");

                    b.Property<decimal?>("StrClickThruRateCtr")
                        .HasColumnType("numeric");

                    b.Property<int?>("StrClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StrCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<string>("StrCurrency")
                        .HasColumnType("text");

                    b.Property<string>("StrCustomerSearchTerm")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StrImpressions")
                        .HasColumnType("integer");

                    b.Property<string>("StrMatchType")
                        .HasColumnType("text");

                    b.Property<string>("StrPortfolioName")
                        .HasColumnType("text");

                    b.Property<decimal?>("StrSpend")
                        .HasColumnType("numeric");

                    b.Property<string>("StrTargeting")
                        .HasColumnType("text");

                    b.Property<decimal?>("StrTotalAdvertisingCostOfSalesAcos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StrTotalReturnOnAdvertisingSpendRoas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SearchTermsReport");
                });

            modelBuilder.Entity("amazonppcapi.Models.Entities.TargetingReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Tr7DayAdvertisedSkuSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Tr7DayAdvertisedSkuUnits")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Tr7DayConversionRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Tr7DayOtherSkuSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Tr7DayOtherSkuUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("Tr7DayTotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Tr7DayTotalSales")
                        .HasColumnType("numeric");

                    b.Property<int?>("Tr7DayTotalUnits")
                        .HasColumnType("integer");

                    b.Property<string>("TrAdGroupName")
                        .HasColumnType("text");

                    b.Property<string>("TrCampaignName")
                        .HasColumnType("text");

                    b.Property<decimal?>("TrClickThruRateCtr")
                        .HasColumnType("numeric");

                    b.Property<int?>("TrClicks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TrCostPerClickCpc")
                        .HasColumnType("numeric");

                    b.Property<string>("TrCurrency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TrImpressions")
                        .HasColumnType("integer");

                    b.Property<string>("TrMatchType")
                        .HasColumnType("text");

                    b.Property<string>("TrPortfolioName")
                        .HasColumnType("text");

                    b.Property<decimal?>("TrSpend")
                        .HasColumnType("numeric");

                    b.Property<string>("TrTargeting")
                        .HasColumnType("text");

                    b.Property<decimal?>("TrTotalAdvertisingCostOfSalesAcos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TrTotalReturnOnAdvertisingSpendRoas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TargetingReport");
                });
#pragma warning restore 612, 618
        }
    }
}
